linters-settings:
  funlen:
    lines: 100
    statements: 50
  gci:
    no-inline-comments: true
    no-prefix-comments: true
    sections:
      - standard
      - default
      - prefix(github.com/javorszky/battlesnek)
  goconst:
    min-len: 2
    min-occurrences: 3

  gomnd:
    # don't include the "operation" and "assign"
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '3'
    ignored-functions:
      - strings.SplitN

  govet:
    check-shadowing: true
    lll:
    line-length: 120
  misspell:
    locale: UK

linters:
  disable-all: true
  enable:
    - deadcode
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gci
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace
    - wsl
    - revive

run:
  timeout: 5m
  go: '1.18'
