version: "3.9"

services:
  lintfixer:
    container_name: "lintfixer"
    build:
      context: .
      dockerfile: ./ops/Dockerfile-gci
    volumes:
      - .:/app:rw
    working_dir: /app
    command: ./ops/gci.sh
